### PR TITLE
Switched to AsyncKeyedLock for lower allocations

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**

### CODE REVIEW

**Comment by sa-es-ir** [comment]
Do you have a Benchmark that shows your library is better than the previous one? since I'm not sure about the performance

**Comment by MarkCiliaVincenti** [comment]
> Do you have a Benchmark that shows your library is better than the previous one? since I'm not sure about the performance

The previous library does not have pooling; therefore it has to create a relatively-expensive SemaphoreSlim every time which increases memory allocations.

Furthermore, the current implementation does not seem to be thread safe to me at a quick glance. `InnerSemaphore` has a `_waiters` counter but it does not seem to be incrementing or decrementing within a lock, and undesired results might happen.

A similar library to yours found our implementation useful and is using it. https://github.com/stefanprodan/AspNetCoreRateLimit

**Comment by MarkCiliaVincenti** [comment]
Cool, thanks for the merge! Let me know when you package it into a new NuGet version please :)

**Comment by sa-es-ir** [comment]
@MarkCiliaVincenti Thank you for contributing and sure I'll let you know

**Comment by MarkCiliaVincenti** [comment]
> @MarkCiliaVincenti Thank you for contributing and sure I'll let you know

Cheers, looking forward!

**Comment by MarkCiliaVincenti** [comment]
gentle nudge :)

**Comment by sa-es-ir** [comment]
@MarkCiliaVincenti 
New version 1.0.3 released!

**Comment by MarkCiliaVincenti** [comment]
Brilliant, @sa-es-ir!
But what is this? I think you need to update here as well: https://github.com/sa-es-ir/DotNet.RateLimit/pkgs/nuget/DotNetRateLimiter

**Pull request merged**
